# Generated by Django 5.0.1 on 2024-02-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ichimliklar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichimliklar',
            name='image_drink',
            field=models.ImageField(default=False, upload_to='media/ichimliklar_image'),
        ),
    ]
